import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Explicit sidebar: curated top-level structure, with the generated TypeDoc tree autogenerated
// under the TypeScript SDK section.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Tutorial',
      collapsed: false,
      items: ['tutorial/first-softphone'],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: ['concepts/state-and-events', 'concepts/intents', 'concepts/glossary'],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: ['guides/authentication', 'guides/errors-and-reconnects', 'guides/recipes', 'guides/typescript-vs-go', 'guides/troubleshooting'],
    },
    {
      type: 'category',
      label: 'TypeScript SDK',
      collapsed: false,
      items: [
        'typescript/getting-started',
        'typescript/quickstart-client',
        'typescript/quickstart-control-only',
        'typescript/embedding',
        {
          type: 'category',
          label: 'API reference (TypeDoc)',
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'typescript/api'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Go SDK',
      collapsed: false,
      items: ['go/getting-started', 'go/quickstart-client', 'go/quickstart-control-only'],
    },
    {
      type: 'category',
      label: 'Protocol reference',
      collapsed: false,
      items: [
        'protocol/overview',
        'protocol/grpc',
        {type: 'link', label: 'REST / OpenAPI', href: 'pathname:///reference/rest/'},
        {type: 'link', label: 'Events / AsyncAPI', href: 'pathname:///reference/events/'},
      ],
    },
    'changelog',
  ],
};

export default sidebars;
